### ISSUE TITLE
Impacts of setting NVIDIA_DRIVER_CAPABILITIES=all

### ISSUE THREAD

**Issue by ishaaq** [NVIDIA/nvidia-container-runtime#112]
Can you elaborate what impacts (performance, security, ?) there are of setting `NVIDIA_DRIVER_CAPABILITIES=all`?

In other words: are there any legitimate reasons to set this to anything else other than `all`?

The only reason I can think of is to restrict the use of `display` if you don't want some arbitrary code inside the docker container to have access to the X11 display for security reasons. However, I can't think of any reason to restrict the other capabilities unless perhaps there are some security or performance reasons that I am currently unaware of. Could you shed some light on this please?

Thanks

**Comment by nicklhy** [comment]
+1, same question.

**Comment by klueska** [comment]
For most practical purposes, it should be fine to set `NVIDIA_DRIVER_CAPABILITIES=all` nowadays.

Historically, these different capabilities exist because they were added incrementally, with varying degrees of stability. It's fairly common to run with GPUs in containers nowadays, but a few years ago the driver didn't support them very well, and it was important to make sure the libraries being injected into the container actually worked in a containerized environment. When they didn't, it was common to get information leaks, crashes, or even silent failures.

In the past, whenever a new set of libraries was being vetted for injected, a new capability was added to make sure that users had control to explicitly include only those libraries they were comfortable having injected into their containers.

The idea being that whoever puts together a container image for use with GPUs should have the knowledge of what capabilities the software in that container image requires, and can set the `NVIDIA_DRIVER_CAPABILITIES` envvar in that image appropriately.

**Comment by qhaas** [comment]
A concern nowadays would be [`compat32` being 'enabled' by `all`](https://github.com/NVIDIA/nvidia-container-runtime#nvidia_driver_capabilities).  I'd think 32-bit x86 cuda linux would be deprecated these days, can't imagine that stack being as well tested as x86-64 cuda binaries in Linux.
