### ISSUE TITLE
Debian11 support

### ISSUE THREAD

**Issue by chaiyd** [NVIDIA/nvidia-container-runtime#152]
- Debian11 use systemd（cgroupsv2）by default.
- Nvidia-docker2 do not use privileged，will report `Failed to initialize NVML: Unknown Error`

**Comment by elezar** [comment]
Hi @chaiyd the lack of Debian11 support is a known issue. Please see the workaround discussed in https://github.com/NVIDIA/libnvidia-container/issues/111 and confirmed to work for other distributions such as Ubuntu 21.04 in #158.

Since the workaround is known and addressing this shortcoming is on our roadmap, do you mind closing this issue if you are able to get it working?
