### ISSUE TITLE
Manual build without Docker not possible with v3.6.0?

### ISSUE THREAD

**Issue by ich777** [NVIDIA/nvidia-container-runtime#159]
I've noticed that the complete build process changed with version 3.6.0, is it now not possible anymore to build the container-runtime natively on Debian or any other distribution like Slackware?

**Comment by elezar** [comment]
Hi @ich777. The `nvidia-container-runtime` binary that was included in this repo has been moved to https://github.com/NVIDIA/nvidia-container-toolkit. Since the packaging process is the same in both cases it would still be possible to build the packages there.

That is to say, as of the `3.6.0` release the `nvidia-container-runtime` package is an empty (meta) package that only serves to define a dependency on the `nvidia-container-toolkit` package which contains the components of the NVIDIA container stack.

**Comment by ich777** [comment]
Hi @elezar, thank you for the quick answer and explanation!
Will look into this and report back if I experience any issues, will close this issue and create a new one but hopefully I don't run into any issues. :)

**Comment by elezar** [comment]
Great, thanks! Please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit/issues if something comes up.

**Comment by ich777** [comment]
@elezar FYI, everything is working as expected when compiling nvidia-container-toolkit on Debian 11.
Thank you again for the quick help!

**Comment by elezar** [comment]
Great! Glad to hear that it's working.
