### ISSUE TITLE
Please bring back binary build target

### ISSUE THREAD

**Issue by davidshen84** [NVIDIA/nvidia-container-runtime#162]
Hi,

In v3.5.0, there's a **binary** target that I can use to build for my Gentoo system. But it is removed and I can only find *docker* targets.

**Comment by davidshen84** [comment]
Sorry, I just noticed the `nvidia-container-runtime` binary is built in the `nvidia-container-toolkit` project. So what is the purpose of this project now?

**Comment by elezar** [comment]
@davidshen84 yes, the binary itself was moved to the `nvidia-container-toolkit` project in order to streamline our release process. I missed added a note to the README to explain this change. I will be sure to add it.

This repo still provides a meta package to ensure that workflows that rely on the `nvidia-container-runtime` package be installed work as expected. We have also not yet migrated the issues from this repo to the new repo.
