### ISSUE TITLE
How to install on ubuntu 14.04?

### ISSUE THREAD

**Issue by deddysetyadi** [NVIDIA/nvidia-container-runtime#171]
Hello, I need to install nvidia-container-runtime on ubuntu 14.04 but package not found on apt repository.

I know that this package had dropped support for ubuntu 14.04 on repository, is there any alternative way to install this package manually? 

Thanks

**Comment by elezar** [comment]
@deddysetyadi you could try to build the [`nvidia-container-toolkit`](https://github.com/NVIDIA/nvidia-container-toolkit) and [`libnvidia-container*`](https://github.com/NVIDIA/libnvidia-container) packages from source.

Since there are `ubuntu14.04` docker images available, I would suggest using the containerised builds.
