### ISSUE TITLE
Fedora 35 unsupported, could centos8 work?

### ISSUE THREAD

**Issue by XuYuan114514** [NVIDIA/nvidia-container-runtime#183]
Since Fedora 35 is not in the list of supported distributions, I browsed through other similar issues.  @elezar suggested to use the Centos repositories for installing packages. 
So I run 
```
curl -s -L https://nvidia.github.io/nvidia-container-runtime/centos8/nvidia-container-runtime.repo | \                                                        
  sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo
```
and `sudo yum install nvidia-container-runtime`. 
Then I restart my docker.
But in the end it still failed to run with **[failed](docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].)**
So the code for my installation of centos8 version is wrong, or fedora 35 is not supported？

**Comment by elezar** [comment]
The `cenos8` packages should be compatible with fedora35 since the main limitation would be the minimum glibc version.

Note that your instructions have not added the NVIDIA Container Runtime to the docker `/etc/docker/daemon.json` file which is why You're seeing the error. We are in the process of updating our documentation to make things clearer across operating systems.

Please try the following instructions:

## Add the repositories
```
distribution=centos8 \
                && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.repo | sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
```
**Note:** `distribution` is being overridden to `centos8`


## Install the NVIDIA Container Toolkit
```
sudo dnf clean expire-cache \
                && sudo dnf install -y nvidia-container-toolkit
```
**Note:** the `nvidia-container-toolkit` package is installed

## Add the NVIDIA Container Runtime to the docker config
```
sudo nvidia-ctk runtime configure --runtime=docker
```
## Restart the Docker daemon
```
sudo systemctl restart docker
```

If any of these steps give problems, please let us know.

**Comment by elezar** [comment]
@XuYuan114514 could you confirm that the instructions provided worked for you?

**Comment by elezar** [comment]
Please note the general instructions for all modern RPM-based distrubtions:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-yum-or-dnf
