### ISSUE TITLE
Amazon Linux 2023 support

### ISSUE THREAD

**Issue by bufferoverflow** [NVIDIA/nvidia-container-runtime#192]
I just figured out that you do not support Amazon Linux 2023, any plans to do so or alternative tricks to make it run?

**Comment by elezar** [comment]
@bufferoverflow  We have tested AL2023 internally, but not updated our official support policy.

With the NVIDIA Container Toolkit 1.14.0 release, we have simplified the packaging for the toolking, meaning that the same instructions can be used regardless of distributions. We will be updating our documentation in the coming days. It will reference the following steps:

1. Configure the repository:
```
curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
     sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
```

2. Install the package(s)
```
sudo yum install -y nvidia-container-toolkit
```

3. Configure the runtime (e.g. Docker)
```
sudo nvidia-ctk runtime configure --runtime=docker
```

4. Restart the runtime (e.g. Docker)
```
sudo systemctl restart docker
```

Please let us know if these instructions do not work for you so that we can fix any issues on our end, or update the docuementation.

**Comment by bufferoverflow** [comment]
thanks a lot @elezar I just used your instructions and it works smooth. have a great day!
