### ISSUE TITLE
is it possible to make ncr support openEuler officially？

### ISSUE THREAD

**Issue by liaoyugen** [NVIDIA/nvidia-container-runtime#193]
As title said 
we found the openEuler system was not in the official support ncr os list.
is it possible to make an enhancement ?

**Comment by elezar** [comment]
@liaoyugen I have no experience with openEuler and we don't have plans to officially support it.

With that said, we have recently generalized our [installation instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) so that these may now be applicable.

As noted, this would be without official support. If there are problems open an issue against https://github.com/NVIDIA/nvidia-container-toolkit.
