### ISSUE TITLE
How can I install nvidia-docker2, nvidia-container-runtime  in other linux distributions?

### ISSUE THREAD

**Issue by romarcg** [NVIDIA/nvidia-container-runtime#9]
Hi,

I have been trying to install docker-nvidia2 in Debian (8) Jessie without success. I am able to install 17.12.0~ce-0~debian. As I don't see any mention of "other supported distributions", I wonder if is this installation possible?

Best regards,

**Comment by adzy2k6** [comment]
I am also curious about how to install the runtime on other generic Linux distributions. I currently use Solus on my home desktop, and it would be useful to get this working on that.

**Comment by adzy2k6** [comment]
I managed to figure this out. I initially tried using the version compiled through the ubuntu container, but that didn't work. There isn't a container image for Solus, so I ended up doing the following:

Install go on the linux machine that you intend on using docker on. You also need to set GOPATH to wherever you want o build the filed.

Next, you need to compile the two programs, as they do in the docker file. Create the directories:
src/github.com/opencontainers/runc under your gopath, and navigate to runc. Type:

`git clone https://github.com/docker/runc.git . && \
git fetch https://github.com/opencontainers/runc.git`

Next, you need to find a specific commit, and apply a patch to it. This will vary depending on which docker you have installed, but you can get a hint by looking at the makefile in this repo. Mine was the b256 patch. You will find this under the runc folder in this repo. Place the patch file somewhere you will remember, and type:

`git checkout b256 && git apply $PATH_TO_PATCH/*`

Navigate to your runc directory, and type make. I remember the BUILD_TAGS argument causing issues, so i think I omitted it.

Next, copy the nvidia-contrainer-runtime-hooks directory into the src directory in your gopath. Type ` go get -v nvidia-container-runtime-hook ` to build.

Find the two binaries that were just built. One will be in your runc folder, the other will be under $GOPATH/bin.

Install these binaries under somewhere that is on your path (I think it also needs to be on the global system path).

The final part of this is is the config.toml. I renamed and copied the xenial version. The one thing that I needed to change was the path to ldconfig, to /sbin/ldconfig . After that, install the libnvidia-container.so so that it can be accessed as per the instructions in that repo, and run:

` docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi `

**Comment by flx42** [comment]
Yeah, I need to document this process a bit better. Sorry about that.

**Comment by mingfengwuye** [comment]
I am curious about this too. It may be a guide build from source code

**Comment by flx42** [comment]
Added support for Debian 8 Jessie here: df354ebe1467783359564afa4c8ea1b2b6d0ba94
Packages are online, but didn't add the new instructions yet, but I'm sure you can figure it out from the current Debian 9 instructions :)

**Comment by flx42** [comment]
```
curl -s -L https://nvidia.github.io/nvidia-docker/debian8/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
```

**Comment by flauted** [comment]
I'm in @adzy2k6 's position, trying to install on Solus. I've gotten pretty far in his instructions, but now I'm stuck on installing libnvidia-container. Was wondering if either he or @flx42 could help. Specific problem is that building libnvidia-container the Docker method doesn't seem to cut it, and I don't have bmake to do the make install. Any insights into how to get past this would be much appreciated!

PS: Sorry for posting here as it's really a question about libnvidia-container, but it felt more appropriate in case someone else comes across these instructions.

**Comment by flauted** [comment]
Nevermind. Using container method worked. [Here's](https://github.com/flauted/solus-setup/blob/master/nvidia-docker.sh) my notes, hope they help somebody!

**Comment by aptalca** [comment]
@flx42 you mentioned you would provide compiling info for other platforms. Is there any?

The closest thing I found is what @flauted provided in his link, but even that grabs a precompiled file from an ubuntu build: https://github.com/flauted/solus-setup/blob/master/nvidia-docker.sh#L103

When I go to the source of that build, I see packages pulled from an ubuntu repo: https://github.com/NVIDIA/libnvidia-container/blob/master/.travis.yml#L38
I'm assuming those packages are cuda-misc-headers-8-0 and cuda-nvml-dev-8-0
I can't find the source for those, only gitlab dockerfiles building them by pulling other packages from private repos.

The question is, is it possible to compile nvidia runtime on a different platform like slackware, or am I going to keep hitting dead ends due to closed source for dependencies? I'd rather not go down the rabbit hole any further if the latter is the case.

Thanks

**Comment by flx42** [comment]
> I can't find the source for those, only gitlab dockerfiles building them by pulling other packages from private repos.

They are not private repos. They are public package repositories from NVIDIA. They are just not controlled by Red Hat/Canonical.

For `libnvidia-container,` use the tarball here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.0.0-rc.2
And instructions are here:
https://nvidia.github.io/libnvidia-container/

For `nvidia-container-runtime-hook`, there is a static binary here:
https://github.com/NVIDIA/nvidia-container-runtime/releases/tag/v1.4.0-1
Install it somewhere in your `PATH`.

If you are using a container tool that can handle OCI hooks directly like `runc`, `CRI-O` or `podman`, you can stop here. You are ready to go.

If you are using docker, there is one extra step: install [runc](https://github.c om/opencontainers/runc#building) after applying this patch:
https://github.com/NVIDIA/nvidia-container-runtime/blob/master/runtime/runc/3f2f8b84a77f73d38244dd690525642a72156c64/0001-Add-prestart-hook-nvidia-container-runtime-hook-to-t.patch
Rename the generated binary from `runc` to `nvidia-container-runtime` then register it to the docker daemon:
https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup

**Comment by archenroot** [comment]
Did someone got this working or not? I am interested in Gentoo distro nvidia-docker v2

**Comment by flauted** [comment]
I never used it myself, but there is a Solus package for it now. You might find this helpful:

https://dev.getsol.us/D4519

**Comment by archenroot** [comment]
@flauted - hm, never heard about Solus :-) and its not compatible on-the-fly with Gentoo's portage ebuild system, but maybe can be used as kind of starting point to create a Gentoo ebuild. Thx for link, will check.

**Comment by archenroot** [comment]
On the other hand, Gentoo is capable to install from deb and rpm packages, so maybe I just take dep package and will need to extract whats in there...

Also some notes for Gentoo users, as it has some support of RPM and DEB:
https://wiki.gentoo.org/wiki/RPM
